services:
  - type: web
    name: laravel-postgres
    plan: free
    region: oregon

    # Use Docker runtime
    env: docker

    # Health check endpoint (should return 200)
    healthCheckPath: /api/users

    # Build Command (optional if using Docker, but good for clarity)
    buildCommand: echo "Using Dockerfile for build"

    # Start Command: Run migrations AND start Apache
    startCommand: >
      php artisan migrate --force &&
      apachectl -D FOREGROUND

    # Environment Variables
    envVars:
      - key: APP_NAME
        value: Laravel Docker App
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true  # Keep true temporarily to see errors; set to false later
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

    # Optional: Set custom port (Render uses PORT=10000 by default)
    # But Apache runs on port 80 internally — Render handles the proxy