services:
  - type: web
    name: laravel-postgres
    plan: free
    region: oregon

    # 👇 This tells Render to use Docker
    env: docker

    # Optional: Health check
    healthCheckPath: /api/users

    # Environment Variables
    envVars:
      - key: APP_NAME
        value: Laravel Docker App
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password