services:
  - type: web
    name: laravel-postgres
    plan: free
    region: oregon

    # Use Docker runtime
    env: docker

    # Health check
    healthCheckPath: /api/users

    # Build command (optional but good for clarity)
    buildCommand: echo "Using Dockerfile"

    # No startCommand needed — handled by CMD in Dockerfile
    # If you want, keep it for override:
    # startCommand: /usr/local/bin/start.sh

    # Environment Variables
    envVars:
      - key: APP_NAME
        value: Laravel Docker App
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true  # Keep true to see errors; set to false later
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: DB_SCHEMA
        value: public