services:
  - type: web
    name: laravel-postgres
    plan: free
    region: oregon

    # 👇 This forces PHP environment
    env: php

    # 👇 Explicitly disable Node.js auto-detection
    buildCommand: |
      echo "Starting PHP build..."
      # Copy env
      cp .env.example .env
      
      # Install PHP dependencies
      composer install --optimize-autoloader --no-dev
      
      # Generate key
      php artisan key:generate
      
      # Optimize
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      echo "Build complete."

    startCommand: php artisan serve --port=$PORT --host=0.0.0.0

    # 👇 Optional: Speed up build by skipping node_modules
    # If you don't need Vite/NPM builds in production
    skipCheckout: false